name: Update Medium Blog Posts

on:
  schedule:
    - cron: '0 8 * * *' # Her gün sabah 8'de çalışır
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Update blog posts in README
        run: |
          npm install rss-parser
          node update-medium.js

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet && echo "No changes to commit" || git commit -m "Update Medium blog posts"
          git push
